### ISSUE TITLE
Webpack and others

### ISSUE THREAD

**Issue by steida** [yuanyan/halogen#1]
I am not sure it's ok to distribute jsx files, webpack can't recongize it by default and I suppose we should not have to BabelScriptize node.js code. It would quickly escalate into super long and brittle builds.

**Comment by steida** [comment]
Anyway, very nice work.

**Comment by yuanyan** [comment]
@steida Thxs

**Comment by yuanyan** [comment]
@steida Thxs

**Comment by yuanyan** [comment]
@steida Thxs

**Comment by tajo** [comment]
+1, it doesn't work with browserify & babelify 

`import {PulseLoader} from 'halogen';`

`Error : Cannot find module 'reactify' from '/Users/.../node_modules/halogen'`

Obviously, I don't have reactify module in my project (just babelify), but I am not quite sure, why browserify&babelify can't handle the build.

Anyway, it's a good idea to commit the all-in one browserified file without JSX and use it as the main file.

**Comment by yuanyan** [comment]
@tajo Added reactify as dependencies, is it ok in halogen@0.1.4?

**Comment by tajo** [comment]
@yuanyan It is. Thanks! I really like this lib.

**Comment by aybarshazar** [comment]
I got the same error from the latest version (0.1.8) and had to downgrade to 0.1.4 make it work with browserify.
