### ISSUE TITLE
npm package has jsx markup

### ISSUE THREAD

**Issue by bjrmatos** [yuanyan/halogen#6]
In order to the be fully compatible to other users the published package must be a builded file without JSX markup.

The only change required to do this is update the package.json file
```js
// package.json
//.......
"main": "dist/halogen.js",
//.......
```

**Comment by bjrmatos** [comment]
issue related in another repo Hacker0x01/react-datepicker#88

**Comment by yuanyan** [comment]
The same reason with #5
